#WARNING: as this file contains credentials, be sure to set correct file permissions
[irc]
    [irc.libera]
    Server="irc.libera.chat:6667"
    Nick="matterbot"

#[mattermost]
#    [mattermost.work]
#    #do not prefix it wit http:// or https://
#    Server="yourmattermostserver.domain" 
#    Team="yourteam"
#    Login="yourlogin"
#    Password="yourpass"
#    PrefixMessagesWithNick=true

[matrix.mymatrix]
Server="https://matrix.org"

#Use a dedicated user for this and not your own!
#Messages sent from this user will not be relayed to avoid loops.
Login="yourlogin"
Password="yourpass"

#Alternatively you can use MXID and access token (open https://app.element.io/
#in INCOGNITO mode, open Settings -> lowest tab and above "clear cache and reload"
#you can find the access token. Close the window without logging out
#(or the token gets invalid (if it leaks, it can be removed by logging in and using the sessions menu))
#MxID="@yourbot:example.net"
#Token="tokenforthebotuser"

RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

#Whether to send the homeserver suffix. eg ":matrix.org" in @username:matrix.org
#to other bridges, or only send "username".(true only sends username)
#OPTIONAL (default false)
NoHomeServerSuffix=false

[[gateway]]
name="gateway1"
enable=true
    [[gateway.inout]]
    account="irc.libera"
    channel="#testing"

    [[gateway.inout]]
    account="matrix.mymatrix"
    channel="!liberairc:matrix.org"
    
#simpler config possible since v0.10.2
#[[gateway]]
#name="gateway2"
#enable=true
#inout = [
#    { account="irc.libera", channel="#testing", options={key="channelkey"}},
#    { account="mattermost.work", channel="off-topic" },
#]
